language: C
compiler:
  - gcc
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" COMMON_DIR=common MAKE_DIR=server
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" COMMON_DIR=common MAKE_DIR=client

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cd $COMMON_DIR && make && cd ..
  - cd $MAKE_DIR && make
